### ISSUE TITLE
navbar tabs not working properly.

### ISSUE THREAD

**Issue by khokharnikunj8** [COED-SVNIT/svnit_web#10]
tabs in the navbar are not responding properly . should I open PR for this ? @jkachhadia @HimanshuKantharia @piyush666 @jaydeepRadadiya

**Comment by HimanshuKantharia** [comment]
@nik1010 Sorry to inform, but this is an incomplete project, it is updated to latest versions because of security concerns, rest of the project is being carried out in another Private repo.

**Comment by khokharnikunj8** [comment]
@HimanshuKantharia  Thanks.
